### ISSUE TITLE
Unkown function: <SNR>28_chord_key

### ISSUE THREAD

**Issue by blasco** [kana/vim-arpeggio#21]
The latest update fixed the warnings, but now I'm getting the following error:
```
Unkown function: <SNR>28_chord_key
```
What could be causing that? Is this a bug or an error in my config?

It seems to happen when the following plugin is enabled, but I'm pretty sure it wasn't happening before the last update.

https://github.com/takac/vim-hardtime

**Comment by kana** [comment]
I confirmed the error is reproducible with the following configuration:

```vim
Arpeggio nnoremap jf <Esc>
HardTimeOn
" Pressing j causes:
" E117: Unknown function: <SNR>16_chord_key
```

I took a quick look on vim-hardtime, and it could be conflict with vim-arpeggio.  I'll investigate the problem later.

Note that the last update of vim-arpeggio is not relevant to the error.  The error is reproducible with older versions of vim-arpeggio.

**Comment by kana** [comment]
vim-hardtime redefines `j`, `k`, and other basic movement keys.  If user customizes those keys, like `noremap j gj`, [vim-hardtime respects the user's customization](https://github.com/takac/vim-hardtime/blob/d9128568afa62947b7ac8f12c22d88e3de526a6b/plugin/hardtime.vim#L67).

The problem is that vim-hardtime fails to reproduce some kind of mappings.  If `j` and/or other keys are mapped to something that contains `<SID>`, vim-hardtime redefines such mappings in a wrong way. So...

---

```vim
Arpeggio nnoremap jf <Esc>
```

defines a lot of internal key mappings, and one of them is:

```vim
nmap <expr> j <SID>chord_key('j')
```

Since this command is executed by vim-arpeggio, `<SID>` is translated to the actual script ID for vim-arpeggio, like `<SNR>42_`.

---

```vim
HardTimeOn
```

redefines several keys including `j`, and `j` is redefined as follows:

```vim
nnoremap <buffer> <silent> <expr> j TryKey('j') ? <SID>chord_key('j') : TooSoon('j','n')
```

This command is executed by vim-hardtime, so `<SID>` is translated to the actual script ID for vim-hardtime, like `<SNR>28_`.  Note that this is different from the one for vim-arpeggio.

---

vim-hardtime should use the original script ID like `<SNR>42_` instead of `<SID>` to redefine keys.  This is the cause of the problem.

**Comment by blasco** [comment]
Great, I've reported the issue on that plugin.

**Comment by blasco** [comment]
reported to the other plugin.

**Comment by blasco** [comment]
Mmm, but a solution would be very specific for vim-arpeggio, right? From your explanation what I understand is that I need to redefine those vim-hardtime mappings as <SNR>XX_ instead of <SID> where XX is the script id of vim-arpeggio. Is there a way to do this in a generic way? And how can I figure out XX for vim-arpeggio?

**Comment by kana** [comment]
No.

[The code to redefine existing key mappings](https://github.com/takac/vim-hardtime/blob/d9128568afa62947b7ac8f12c22d88e3de526a6b/plugin/hardtime.vim#L67) in vim-hardtime is as follows:

```vim
exec "nnoremap <buffer> <silent> <expr> " . i . " TryKey('" . i . "') ? " . s:RetrieveMapping(i, "n") . " : TooSoon('" . ii . "','n')"
```

Where [`s:RetrieveMapping`](https://github.com/takac/vim-hardtime/blob/d9128568afa62947b7ac8f12c22d88e3de526a6b/plugin/hardtime.vim#L48-L58) is the function to retrieve the information about an existing key mapping.  It is a wrapper for [`maparg`](https://github.com/vim/vim/blob/8b530c1ff91f07cf6b0289a536992b7dfbc86598/runtime/doc/eval.txt#L6679-L6733), and `maparg` returns [enough data, including `sid`](https://github.com/vim/vim/blob/8b530c1ff91f07cf6b0289a536992b7dfbc86598/runtime/doc/eval.txt#L6723-L6724), for a proper redefinition.

So that all we have to do is to tweak `s:RetrieveMapping` to replace `<SID>` with `<SNR>XXX_`, where `XXX` is the value of `sid` returned by `maparg`.

**Comment by blasco** [comment]
Ok, I'm on it :) I'll let you know where I get

**Comment by blasco** [comment]
The following seems to be working for me, how does it look to you?

```
fun! s:RetrieveMapping(key, mode)
    let mapping = maparg(a:key, a:mode, 0, 1)
    if !has_key(mapping, "rhs") || mapping["rhs"] == ""
        return "'" . a:key . "'"
    endif
    if  has_key(mapping, "sid")
        let mapping["rhs"] = substitute(mapping["rhs"], "<SID>", "<SNR>".mapping["sid"]."_", "")
    endif
    " If mapping is an expression, don't quote
    if mapping["expr"]
        return mapping["rhs"]
    endif
    return "'" . mapping["rhs"] . "'"
endf
```

**Comment by kana** [comment]
It looks good other than the followings:

- `mapping["rhs"]` might contain multiple `<SID>`s, so the 4th argument to `substitute()` should be `"g"` instead of `""`.
- The `if` is always true at that context, so it can be removed.

**Comment by blasco** [comment]
`   if  has_key(mapping, "sid")` is always true? Ok, so then just like this:
```
fun! s:RetrieveMapping(key, mode)
    let mapping = maparg(a:key, a:mode, 0, 1)
    if !has_key(mapping, "rhs") || mapping["rhs"] == ""
        return "'" . a:key . "'"
    endif

    let mapping["rhs"] = substitute(mapping["rhs"], "<SID>", "<SNR>".mapping["sid"]."_", "g")

    " If mapping is an expression, don't quote
    if mapping["expr"]
        return mapping["rhs"]
    endif
    return "'" . mapping["rhs"] . "'"
endf
```
This is the only addition:
```
 let mapping["rhs"] = substitute(mapping["rhs"], "<SID>", "<SNR>".mapping["sid"]."_", "g")
```

**Comment by kana** [comment]
Perfect!

**Comment by blasco** [comment]
Great!, thank you for the guidance. PR updated at vim-hardtime project

**Comment by blasco** [comment]
Just in case somebody runs into this issue, while they accept the PR they can use my fork and also it is important to add these mappings:

```
nnoremap <expr> h "h"
nnoremap <expr> j "j"
nnoremap <expr> k "k"
nnoremap <expr> l "l"
```
I'm not sure why, but without that it doesn't work. With that it works and arpeggios also work simultaneously (can you maybe come up with an explanation Kana?)

**Comment by kana** [comment]
Would you mind pasting a minimal and complete configuration ([like this](https://github.com/kana/vim-arpeggio/issues/21#issuecomment-544245127)) to reproduce the problem?  It's hard to answer without the order of definitions you used.

**Comment by blasco** [comment]
You need to be using my fork:
https://github.com/blasco/vim-hardtime

Juest defining some mapping that overlaps with h,j,k,l reproduces the problem:

```
" Window Movement
silent Arpeggio nnoremap <silent> wh :wincmd h<CR>
silent Arpeggio nnoremap <silent> wj :wincmd j<CR>
silent Arpeggio nnoremap <silent> wk :wincmd k<CR>
silent Arpeggio nnoremap <silent> wl :wincmd l<CR>
silent Arpeggio nnoremap <silent> wq :wincmd q<CR>

" ------------------
" vim-hardtime
" ------------------
let g:hardtime_showmsg=1
autocmd FileType cpp,typescript,html,scss execute "HardTimeOn"
let g:hardtime_default_on=0
let g:hardtime_ignore_buffer_patterns = [ "NERD.*" ]
let g:hardtime_timeout=500

" Thefining the following fixes the issue for some unknown reason
nnoremap <expr> h "h"
nnoremap <expr> j "j"
nnoremap <expr> k "k"
nnoremap <expr> l "l"
```

**Comment by kana** [comment]
Hmm, there are multiple problems... the root of the problems is simple: the pull request you made is not pefect yet.

---

There are TWO bugs in vim-hardtime. When vim-hardtime overrides existing key mappings,

(a) It doesn't consider `<SID>` in existing key mappings, and
(b) It doesn't consider whether existing key mappings should be remapped or not.

The pull request fixes (a), but (b) is not fixed yet.

---

```vim
Arpeggio nnoremap <silent> wj :wincmd j<CR>
```

This is actually translated into a bunch of `map` commands. One of them is:

```vim
nmap <expr> j <SID>chord_key('j')
```

Note that this key mapping is defined with `nmap`.

When `HardTimeOn` is executed, `j` is redefined as follows (assuming `<SID>` is properly translated):

```vim
nnoremap <buffer> <silent> <expr> j TryKey('j') ? <SNR>42_chord_key('j') : TooSoon('j','n')
```

Since the original key mapping is defined with `nmap`, `nmap` should be used instead of `nnoremap` in this case.  That's why arpeggio key mappings still don't work with vim-hardtime.

---

```vim
Arpeggio nnoremap <silent> wj :wincmd j<CR>
HardTimeOn
```

Resulting key mappings by the above configuration work as follows.

- Solely typed `w`
  - This does the default behaviour.
- Solely typed `j`
  - This does nothing in most cases.  Because `j` is translated into a random command that just causes beep.
- Repeatedly typed `j`
  - This is ignored by vim-hardtime.
- Simulteneously typed `w` and `j`, **but `w` is actually typed first**
  - This does `wincmd j`.
- Simulteneously typed `w` and `j`, **but `j` is actually typed first**
  - This is equivalent to "solely typed `j`" then "solely typed `w`". vim-arpeggio can't detect this case, because `j` is wrongly redefined by vim-hardtime.

```vim
Arpeggio nnoremap <silent> wj :wincmd j<CR>
nnoremap <expr> j "j"
HardTimeOn
```

This is a simplified version of your example with the workaround.  Result key mappings work as follows:

- Solely typed `w`
  - This does the default behaviour.
- Solely typed `j`
  - This does the default behaviour.  **The workaround fixes only this case.**
- Repeatedly typed `j`
  - This is ignored by vim-hardtime.
- Simulteneously typed `w` and `j`, **but `w` is actually typed first**
  - This does `wincmd j`.
- Simulteneously typed `w` and `j`, **but `j` is actually typed first**
  - This is equivalent to "solely typed `j`" then "solely typed `w`". vim-arpeggio can't detect this case, because `j` is redefined by the workaround.

So that the workaround doesn't fix all problems.
