### ISSUE TITLE
Arpeggio with capital letter

### ISSUE THREAD

**Issue by blasco** [kana/vim-arpeggio#22]
Is it possible to define arpeggios with capital letters? According to the docs we can define arpeggios with 2 or more keys, so I guess it might be possible, but:

This works:
```
Arpeggio map <leader>f <plug>(plug-fun_f)
```

This doesn't:
```
Arpeggio map <leader>F <plug>(plug-fun_F)
```

Is this a limitation or can this be achieved?

**Comment by kana** [comment]
It depends on what keyboard, terminal and/or version of Vim you use, not limited by vim-arpeggio.

IIRC you use `<Space>` as your `<Leader>`.  I guess that:

- You simultaneously typed `<Space>` and `f` while holding down a Shift key,
- In most terminals `<S-Space>` (= Shift + `<Space>`) can't be distinguished from solely typed `<Space>`, but they are distinguishable for some versions of Vim like gvim,
- So your arpeggio mapping was not used because `<Space>` and `F` were not treated as simultaneously typed in your Vim.

Check your Vim distinguishes `<Space>` and `<S-Space>`, for example:

```vim
inoremap <Space> Space
inoremap <S-Space> Shift-Space
```

If `<S-Space>` is recognized in your Vim, tweak your arpeggio mapping a bit like:

```vim
Arpeggio map <S-Space>F <plug>(plug-fun_F)
```

**Comment by blasco** [comment]
You are right. Unfortunately my terminal doesn't seem to detect the difference, but it is working in gvim.
