### ISSUE TITLE
Having problems with / mapping

### ISSUE THREAD

**Issue by blasco** [kana/vim-arpeggio#23]
I'm having trouble with vim-easymotion. The following works:
```
map / <plug>(easymotion-sn)
noremap <leader>/ /\v
```
but using Arpeggio seems to break it:
```
map / <plug>(easymotion-sn)
silent Arpeggio noremap <leader>/ /\v
```
I've been trying different options but I cannot figure out the reason, any suggestion about what could be causing this?

**Comment by kana** [comment]
If you want to map a key which is used as a part of arpeggio mappings, use [`<Plug>(arpeggio-default:{X})`](https://github.com/kana/vim-arpeggio/blob/5d73721898d2bb669ead417b4d3370921ce7c3cf/doc/arpeggio.txt#L254-L258).  For example:

```vim
map <Plug>(arpeggio-default:/) <plug>(easymotion-sn)
```

---

vim-arpeggio defines tons of key mappings to detect what keys are simultaneously pressed.  For example,

```vim
silent Arpeggio noremap <leader>/ /\v
```

this can be translated into something like:

```vim
noremap <script> <leader> <SID>magic-stuff:<leader>
noremap <script> / <SID>magic-stuff:/
...
```

So that

```vim
map / <plug>(easymotion-sn)
```

is overridden by vim-arpeggio.  vim-arpeggio shows a warning about this overriding, but you `silent` it.

**Comment by blasco** [comment]
That's true, I read it in another issue but I forgot. Thank you for the clear explanation.
